# Generated by Django 5.2.7 on 2025-10-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_droit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.AddField(
            model_name='conversation',
            name='bot_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
